<?php
$this->layout('layout::default', ['title' => 'Detail']);

$emptyImage = 'data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22250%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20250%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16de660b39d%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A13pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16de660b39d%22%3E%3Crect%20width%3D%22200%22%20height%3D%22250%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2256.1953125%22%20y%3D%22131%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E';
$poster = $movie->getImage() ?: $emptyImage;

$categories = implode(
    ', ',
    array_map(
        function (CoiSA\MovieList\Entity\Genre $genre) {
            return $genre->getName();
        },
        $movie->getGenres()
    )
);
?>

<?php if ($movie->getBackdrop()): ?><img class="card-img-top" src="<?php echo (string) $movie->getBackdrop(); ?>" /><?php endif; ?>

<div class="card flex-md-row mb-4 box-shadow h-md-250">
    <div class="card-body d-flex flex-column align-items-start">
        <h3 class="mb-0"><?php echo $movie->getName(); ?></h3>
        <?php if ($movie->getReleaseDate()): ?><div class="mb-1 text-muted"><?php echo $movie->getReleaseDate()->format('D, d M Y'); ?></div><?php endif; ?>
        <p class="card-text mb-auto"><?php echo $movie->getOverview() ?: 'No overview was provided'; ?></p>
        <strong class="d-inline-block mb-2 text-primary"><?php echo $categories; ?></strong>
    </div>
    <img class="card-img-right flex-auto d-none d-md-block" style="width: 200px; height: 250px;" src="<?php echo $poster; ?>">
</div>

<a href="javascript:window.history.back();" class="btn btn-sm btn-outline-secondary">Go back</a>
