<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        <title><?php echo $this->e($title ?? 'CoiSA\\MovieList Web App')?></title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />

        <style>
            body { padding-top: 70px; }
            .app { min-height: 100vh; }
            .app-footer { padding-bottom: 1em; }
            h2 a { color: #68b604; }
        </style>

        <?php echo $this->section('stylesheets'); ?>
    </head>
    <body class="app">
        <header class="app-header">
            <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="/">Upcoming Movies</a>
                    </div>
                    <form class="form-inline" action="/search" method="get">
                        <input name="query" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" value="<?php echo $_GET['query'] ?? ''; ?>">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </nav>
        </header>

        <div class="app-content">
            <main class="container">
                <?php echo $this->section('content'); ?>
            </main>
        </div>

        <footer class="app-footer">
            <div class="container">
                <hr />
                <?php echo $this->section('footer'); ?>
            </div>
        </footer>

        <?php echo $this->section('javascript'); ?>
    </body>
</html>
